### ISSUE TITLE
Adapt SVG-Generator Template

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/visualisation#3]
1. add a flag to the generator (e.g. `-onlineIDE`)
2. if this flag is active, add additional code to the svg and html files so that it opens the curresponding file in the editor when I am clicking at the component

I did it manually for the bumperbot, please take a look at:
https://github.com/EmbeddedMontiArc/Demos/blob/master/bumperbot.zip

The changes are `.c9/svg/`.

**Comment by ManuelSchrick** [comment]
Why should this code only get added when the ``-onlineIDE`` flag is set? It works perfectly fine with the code outside of the IDE.

**Comment by ManuelSchrick** [comment]
I added the flag ``--onlineIDE`` now. It should work as expected.
